plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - StateSpaceModel.md
markdown: kramdown
theme: jekyll-theme-cayman
kramdown:
    math_engine: katex
